name: CI

on: push

jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: actions/checkout@v2

      - name: Lint and test
        run: ./gradlew ktlintCheck ktlintTestSourceSetCheck ktlintAndroidTestSourceSetCheck lintDebug testDebugUnitTest --stacktrace

      - name: Publish test reports
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: sample-learning-app/build/reports
        if: ${{ failure() }}
